# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: healthinsurancecard.com
    # EnableNodeOUs: true
    CA:
        Country: VN
        Province: Ho Chi Minh
        Locality: Tan Binh
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname:orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Hospital
  # ---------------------------------------------------------------------------
  - Name: Hospital
    Domain: hospital.healthinsurancecard.com
    EnableNodeOUs: true
    CA:
        Country: VN
        Province: Ho Chi Minh
        Locality: Tan Binh
    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    Template:
      Count: 2
      # ---------------------------------------------------------------------------
      # "Users"
      # ---------------------------------------------------------------------------
      Users:
        Count: 1
  # ---------------------------------------------------------------------------
  # Insurer
  # ---------------------------------------------------------------------------
  - Name: Insurer
    Domain: insurer.healthinsurancecard.com
    EnableNodeOUs: true
    CA:
        Country: VN
        Province: Ho Chi Minh
        Locality: Tan Binh
    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    Template:
      Count: 2
      # ---------------------------------------------------------------------------
      # "Users"
      # ---------------------------------------------------------------------------
      Users:
        Count: 1

