NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.insurerorg.card.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.insurerorg.card.com-cert.pem
    OrganizationalUnitIdentifier: peer
