
version: '2'

networks:
  custom:

services:

  ca.devorg.card.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-devorg
      - FABRIC_CA_SERVER_CA_CERTIFICATE=/etc/hyperledger/fabric-ca-server/ca.devorg.card.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/3ef26b6c7bfed911e3b6ad92e92706be7b65596c7c82980070219af325101424_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/devorg.card.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca.devorg.card.com
    networks:
      - custom

  orderer.card.com:
    container_name: orderer.card.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDER_GENERAL_LOGLEVEL=debug
      - ORDER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDER_GENERAL_GENESISMETHOD=file
      - ORDER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    networks:
      - custom
    ports:
      - 7050:7050
    volumes:
      - ./config/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/card.com/orderers/orderer.card.com/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/devorg.card.com/peers/peer0.devorg.card.com/:/etc/hyperledger/msp/peerDevOrg

  peer0.devorg.card.com:
    container_name: peer0.devorg.card.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.devorg.card.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=DevOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.devorg.card.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - custom
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/devorg.card.com/peers/peer0.devorg.card.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/devorg.card.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
    depends_on:
      - orderer.card.com

